services:
  - type: web
    name: smart-sprayer-api
    env: python
    region: oregon
    plan: free
    rootDir: smart-sprayer
    buildCommand: pip install -r requirements.txt && python seed.py
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
